/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;


import java.util.List;
import javax.swing.table.DefaultTableModel;
import Repositorys.*;
import Objects.*;
import Helper.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;



/**
 *
 * @author Luminescenents
 */
public class MainMenu extends javax.swing.JFrame {

    BahanBakuRepo bahanBakuRepo = new BahanBakuRepo();
    jenisMetricRepo  jenisMetricRepo = new jenisMetricRepo();
    TableConfig tableConfig = new TableConfig();
    tableRefresher tableRefresher = new tableRefresher();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
       tableRefresher.refreshGetAllDataTableBahan(bahanBakuTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanelParent = new javax.swing.JPanel();
        kategoriBtn = new javax.swing.JButton();
        bahanBakuBtn = new javax.swing.JButton();
        resepBtn = new javax.swing.JButton();
        jenisUnitBtn = new javax.swing.JButton();
        headerParent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        bahanBaku = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bahanBakuTable = new javax.swing.JTable();
        cariByNameBtn = new javax.swing.JButton();
        cariByNameField = new javax.swing.JTextField();
        insertDataBtn = new javax.swing.JButton();
        editDataBaku = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        report = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cariByNameField1 = new javax.swing.JTextField();
        cariByNameBtn1 = new javax.swing.JButton();
        insertDataBtn1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        editDataBaku1 = new javax.swing.JButton();
        kategoriPanel = new javax.swing.JPanel();
        cariKategoriField = new javax.swing.JTextField();
        cariKategoriBtn = new javax.swing.JButton();
        addKategoriBtn = new javax.swing.JButton();
        refreshKategori = new javax.swing.JButton();
        editKategori = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        kategoriTable = new javax.swing.JTable();
        unitMetric = new javax.swing.JPanel();
        cariJenisMetricField = new javax.swing.JTextField();
        cariBtnUnit = new javax.swing.JButton();
        insertDataBtnUnit = new javax.swing.JButton();
        refreshBtnUnit = new javax.swing.JButton();
        editDataBtnUnit = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jenisUnitTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanelParent.setBackground(new java.awt.Color(255, 102, 102));

        kategoriBtn.setText("Kategori");
        kategoriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriBtnActionPerformed(evt);
            }
        });

        bahanBakuBtn.setText("Bahan baku");
        bahanBakuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bahanBakuBtnActionPerformed(evt);
            }
        });

        resepBtn.setText("Resep");
        resepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resepBtnActionPerformed(evt);
            }
        });

        jenisUnitBtn.setText("Jenis Unit Metric");
        jenisUnitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisUnitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelParentLayout = new javax.swing.GroupLayout(sidePanelParent);
        sidePanelParent.setLayout(sidePanelParentLayout);
        sidePanelParentLayout.setHorizontalGroup(
            sidePanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelParentLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(sidePanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jenisUnitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kategoriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(sidePanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelParentLayout.createSequentialGroup()
                    .addContainerGap(28, Short.MAX_VALUE)
                    .addComponent(bahanBakuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );
        sidePanelParentLayout.setVerticalGroup(
            sidePanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelParentLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(resepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kategoriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jenisUnitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(sidePanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidePanelParentLayout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(bahanBakuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(439, Short.MAX_VALUE)))
        );

        getContentPane().add(sidePanelParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        headerParent.setBackground(new java.awt.Color(255, 102, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Recipe Management Sytem :D");

        javax.swing.GroupLayout headerParentLayout = new javax.swing.GroupLayout(headerParent);
        headerParent.setLayout(headerParentLayout);
        headerParentLayout.setHorizontalGroup(
            headerParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerParentLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(555, Short.MAX_VALUE))
        );
        headerParentLayout.setVerticalGroup(
            headerParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerParentLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(headerParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 1, 1170, 80));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1157, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 586, 1157, -1));

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));

        bahanBakuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Bahan", "Nama Bahan", "Keterangan", "Foto", "Option"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bahanBakuTable.setRowHeight(30);
        jScrollPane1.setViewportView(bahanBakuTable);

        cariByNameBtn.setText("Cari");
        cariByNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariByNameBtnActionPerformed(evt);
            }
        });

        insertDataBtn.setText("Masukan Data Bahan Baru");
        insertDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDataBtnActionPerformed(evt);
            }
        });

        editDataBaku.setText("Edit Data");
        editDataBaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataBakuActionPerformed(evt);
            }
        });

        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        report.setText("report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bahanBakuLayout = new javax.swing.GroupLayout(bahanBaku);
        bahanBaku.setLayout(bahanBakuLayout);
        bahanBakuLayout.setHorizontalGroup(
            bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bahanBakuLayout.createSequentialGroup()
                .addGroup(bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bahanBakuLayout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(cariByNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cariByNameBtn))
                    .addGroup(bahanBakuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertDataBtn)
                    .addComponent(editDataBaku, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(report))
                .addContainerGap())
        );
        bahanBakuLayout.setVerticalGroup(
            bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bahanBakuLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariByNameBtn)
                    .addComponent(cariByNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bahanBakuLayout.createSequentialGroup()
                        .addComponent(insertDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editDataBaku, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(report)))
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("tab1", bahanBaku);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        cariByNameBtn1.setText("Cari");
        cariByNameBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariByNameBtn1ActionPerformed(evt);
            }
        });

        insertDataBtn1.setText("Masukan Resep Baru");
        insertDataBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDataBtn1ActionPerformed(evt);
            }
        });

        jButton7.setText("Refresh");

        editDataBaku1.setText("Edit Data");
        editDataBaku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataBaku1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cariByNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cariByNameBtn1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertDataBtn1)
                    .addComponent(editDataBaku1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariByNameBtn1)
                    .addComponent(cariByNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(insertDataBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editDataBaku1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        cariKategoriBtn.setText("Cari");
        cariKategoriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariKategoriBtnActionPerformed(evt);
            }
        });

        addKategoriBtn.setText("Masukan Kategori Baru");
        addKategoriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addKategoriBtnActionPerformed(evt);
            }
        });

        refreshKategori.setText("Refresh");

        editKategori.setText("Edit Data");
        editKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editKategoriActionPerformed(evt);
            }
        });

        kategoriTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No Kategori", "Nama_Kategori", "Tipe Taggable"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(kategoriTable);

        javax.swing.GroupLayout kategoriPanelLayout = new javax.swing.GroupLayout(kategoriPanel);
        kategoriPanel.setLayout(kategoriPanelLayout);
        kategoriPanelLayout.setHorizontalGroup(
            kategoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kategoriPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(kategoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kategoriPanelLayout.createSequentialGroup()
                        .addComponent(cariKategoriField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cariKategoriBtn))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(kategoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addKategoriBtn)
                    .addComponent(editKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        kategoriPanelLayout.setVerticalGroup(
            kategoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kategoriPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(kategoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariKategoriBtn)
                    .addComponent(cariKategoriField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kategoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kategoriPanelLayout.createSequentialGroup()
                        .addComponent(addKategoriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(refreshKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", kategoriPanel);

        cariJenisMetricField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariJenisMetricFieldActionPerformed(evt);
            }
        });

        cariBtnUnit.setText("Cari");
        cariBtnUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnUnitActionPerformed(evt);
            }
        });

        insertDataBtnUnit.setText("Masukan Jenis Unit Baru");
        insertDataBtnUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDataBtnUnitActionPerformed(evt);
            }
        });

        refreshBtnUnit.setText("Refresh");
        refreshBtnUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnUnitActionPerformed(evt);
            }
        });

        editDataBtnUnit.setText("Edit Data");
        editDataBtnUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataBtnUnitActionPerformed(evt);
            }
        });

        jenisUnitTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jenisUnitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Metric", "Nama Unit", "Keterangan", "Option"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jenisUnitTable.setFocusCycleRoot(true);
        jenisUnitTable.setRowHeight(35);
        jScrollPane4.setViewportView(jenisUnitTable);

        javax.swing.GroupLayout unitMetricLayout = new javax.swing.GroupLayout(unitMetric);
        unitMetric.setLayout(unitMetricLayout);
        unitMetricLayout.setHorizontalGroup(
            unitMetricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitMetricLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(unitMetricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(unitMetricLayout.createSequentialGroup()
                        .addComponent(cariJenisMetricField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cariBtnUnit))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(unitMetricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertDataBtnUnit)
                    .addComponent(editDataBtnUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtnUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        unitMetricLayout.setVerticalGroup(
            unitMetricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitMetricLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(unitMetricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariBtnUnit)
                    .addComponent(cariJenisMetricField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(unitMetricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(unitMetricLayout.createSequentialGroup()
                        .addComponent(insertDataBtnUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(refreshBtnUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editDataBtnUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", unitMetric);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel6);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab6", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 47, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    
    
    private void bahanBakuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bahanBakuBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        tableRefresher.refreshGetAllDataTableBahan(bahanBakuTable);
    }//GEN-LAST:event_bahanBakuBtnActionPerformed

    private void resepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resepBtnActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_resepBtnActionPerformed

    private void jenisUnitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisUnitBtnActionPerformed
        // TODO add your handling code here:
                 jTabbedPane1.setSelectedIndex(3);
                 tableRefresher.refreshGetAllDataTableJenisUnit(jenisUnitTable);
                 
                 

    }//GEN-LAST:event_jenisUnitBtnActionPerformed

    private void editDataBakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataBakuActionPerformed
        // TODO add your handling code here:
        editBahanBaku2 editBahanBaku = new editBahanBaku2();
        editBahanBaku.setVisible(true);
    }//GEN-LAST:event_editDataBakuActionPerformed

    private void insertDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataBtnActionPerformed
        // TODO add your handling code here:
        TambahBahanBakuForm tambahBakuPage = new TambahBahanBakuForm();
        tambahBakuPage.setVisible(true);

    }//GEN-LAST:event_insertDataBtnActionPerformed

    private void kategoriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriBtnActionPerformed
         jTabbedPane1.setSelectedIndex(2);
         
        tableRefresher.refreshGetAllDataTableKategori(kategoriTable);
    
    }//GEN-LAST:event_kategoriBtnActionPerformed

    private void cariByNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariByNameBtnActionPerformed
        // TODO add your handling code here:
        
        
        
        BahanBaku cariBahan = new BahanBaku(cariByNameField.getText());
        
        

        DefaultTableModel model = (DefaultTableModel) bahanBakuTable.getModel();
         tableConfig.removeAllData(model);

        
       List<BahanBaku> bahanBakuList =  bahanBakuRepo.getBahanBakuByName(cariBahan);
        if(bahanBakuRepo.getAllBahanBaku() != null){
            
                for (int i = 0; i < bahanBakuList.size(); i++) {
                    BahanBaku bahanBakuValue = bahanBakuList.get(i);
                    // Lakukan sesuatu dengan setiap objek Mahasiswa
                    String No_bahan_baku = bahanBakuValue.getNo_bahan_baku();
                    String Nama_bahan = bahanBakuValue.getNama_bahan();
                    String getKeterangan = bahanBakuValue.getKeterangan();
                    model.addRow(new String[] {No_bahan_baku, Nama_bahan, getKeterangan});
                   
                }

    }
        
    }//GEN-LAST:event_cariByNameBtnActionPerformed

    private void cariByNameBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariByNameBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariByNameBtn1ActionPerformed

    private void insertDataBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertDataBtn1ActionPerformed

    private void editDataBaku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataBaku1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editDataBaku1ActionPerformed

    private void cariKategoriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariKategoriBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariKategoriBtnActionPerformed

    private void addKategoriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addKategoriBtnActionPerformed
        // TODO add your handling code here:
        
        tambahKategori tambahKategori = new tambahKategori();
        tambahKategori.setVisible(true);
    }//GEN-LAST:event_addKategoriBtnActionPerformed

    private void editKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editKategoriActionPerformed
        // TODO add your handling code here:
        editKategori editKategori = new editKategori();
        editKategori.setVisible(true);
    }//GEN-LAST:event_editKategoriActionPerformed

    private void cariBtnUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnUnitActionPerformed
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) jenisUnitTable.getModel();
          tableConfig.removeAllData(model);
       
        
        
        
        List<JenisMetric> jenisMetricList =   jenisMetricRepo.getJenisMetricByName(cariJenisMetricField.getText());
        if(jenisMetricList != null){
            
                for (int i = 0; i < jenisMetricList.size(); i++) {
                    JenisMetric jenisMetricValue = jenisMetricList.get(i);
                    // Lakukan sesuatu dengan setiap objek Mahasiswa
                    String no_metric = jenisMetricValue.getNo_metric();
                    String nama_metric = jenisMetricValue.getNama_metric();
                    String keterangan = jenisMetricValue.getKeterangan();
                    model.addRow(new String[] {no_metric, nama_metric, keterangan});
                   
                }

    }
    }//GEN-LAST:event_cariBtnUnitActionPerformed

    private void insertDataBtnUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataBtnUnitActionPerformed
        // TODO add your handling code here:
        tambahDataJenisUnit tambahDataJenisUnit = new tambahDataJenisUnit();
        tambahDataJenisUnit.setVisible(true);
    }//GEN-LAST:event_insertDataBtnUnitActionPerformed

    private void editDataBtnUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataBtnUnitActionPerformed
        // TODO add your handling code here:
        
        editDataJenisUnit editDataJenisUnit = new editDataJenisUnit();
        editDataJenisUnit.setVisible(true);
    }//GEN-LAST:event_editDataBtnUnitActionPerformed

    private void cariJenisMetricFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariJenisMetricFieldActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_cariJenisMetricFieldActionPerformed

    private void refreshBtnUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnUnitActionPerformed
        // TODO add your handling code here:
        tableRefresher.refreshGetAllDataTableJenisUnit(jenisUnitTable);
    }//GEN-LAST:event_refreshBtnUnitActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:\
        tableRefresher.refreshGetAllDataTableBahan(bahanBakuTable);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
    try {


        // Create a JRDataSource from the ResultSet
//        JRResultSetDataSource jrRS = new JRResultSetDataSource(the resut);

        // Compile the JasperReport file
//        JasperReport jasperReport = JasperCompileManager.compileReport("testReport2.jrxml");

        // Fill the report with data
//        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);

        // Create a JRViewer to display the report
//        JRViewer jrViewer = new JRViewer(jasperPrint);

        // Create a JDialog to show the report
//        JDialog dialog = new JDialog();
//        dialog.setTitle("Jasper Report");
//        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
//        dialog.getContentPane().add(jrViewer);
//        dialog.pack();
//        dialog.setLocationRelativeTo(null);
//        dialog.setVisible(true);


    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error generating report: " + e.getMessage());
    }
    }//GEN-LAST:event_reportActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addKategoriBtn;
    private javax.swing.JPanel bahanBaku;
    private javax.swing.JButton bahanBakuBtn;
    private javax.swing.JTable bahanBakuTable;
    private javax.swing.JButton cariBtnUnit;
    private javax.swing.JButton cariByNameBtn;
    private javax.swing.JButton cariByNameBtn1;
    private javax.swing.JTextField cariByNameField;
    private javax.swing.JTextField cariByNameField1;
    private javax.swing.JTextField cariJenisMetricField;
    private javax.swing.JButton cariKategoriBtn;
    private javax.swing.JTextField cariKategoriField;
    private javax.swing.JButton editDataBaku;
    private javax.swing.JButton editDataBaku1;
    private javax.swing.JButton editDataBtnUnit;
    private javax.swing.JButton editKategori;
    private javax.swing.JPanel headerParent;
    private javax.swing.JButton insertDataBtn;
    private javax.swing.JButton insertDataBtn1;
    private javax.swing.JButton insertDataBtnUnit;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jenisUnitBtn;
    private javax.swing.JTable jenisUnitTable;
    private javax.swing.JButton kategoriBtn;
    private javax.swing.JPanel kategoriPanel;
    private javax.swing.JTable kategoriTable;
    private javax.swing.JButton refreshBtnUnit;
    private javax.swing.JButton refreshKategori;
    private javax.swing.JButton report;
    private javax.swing.JButton resepBtn;
    private javax.swing.JPanel sidePanelParent;
    private javax.swing.JPanel unitMetric;
    // End of variables declaration//GEN-END:variables
}
