/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import Objects.Kategori;
import Repositorys.TaggableRepo;
import Repositorys.KategoriRepo;
import Objects.Taggable;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.WindowConstants;

/**
 *
 * @author Luminescenents
 */
public class tambahKategori extends javax.swing.JFrame {
TaggableRepo taggableRepo = new TaggableRepo();
KategoriRepo kategoriRepo = new KategoriRepo();
Taggable taggables;
Kategori kategori;
//    ArrayList<Taggable> taggableList = new ArrayList<>();

    /**
     * Creates new form tambahKategori
     */
    public tambahKategori() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    public Kategori getAllDataKategoriField(){
 
      String taggable = (String) taggableCombo.getSelectedItem();
      Taggable taggableValue = taggableRepo.getTaggableByName(taggable);
        
      String namaKategori = namaKategoriField.getText();
      return new Kategori(namaKategori,taggableValue.getId_taggable());
}
    
public Taggable getAllDataTaggableField(){
       String taggable = (String) taggableCombo.getSelectedItem();
       Taggable taggableValue = taggableRepo.getTaggableByName(taggable);
       return new Taggable(taggableValue.getTipe_taggable());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelAddBahan = new javax.swing.JPanel();
        namaBahan = new javax.swing.JLabel();
        tambahBtn = new javax.swing.JButton();
        ket = new javax.swing.JLabel();
        namaKategoriField = new javax.swing.JTextField();
        namaBahan2 = new javax.swing.JLabel();
        taggableCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAddBahan.setBackground(new java.awt.Color(255, 255, 255));
        panelAddBahan.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        namaBahan.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        namaBahan.setForeground(new java.awt.Color(51, 153, 255));
        namaBahan.setText("Nama Kategori");

        tambahBtn.setText("Tambah Data ! :D");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        ket.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        ket.setForeground(new java.awt.Color(51, 153, 255));
        ket.setText("Tipe Kategori");

        namaBahan2.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        namaBahan2.setForeground(new java.awt.Color(51, 153, 255));

        taggableCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taggableCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        taggableCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taggableComboFocusGained(evt);
            }
        });

        javax.swing.GroupLayout panelAddBahanLayout = new javax.swing.GroupLayout(panelAddBahan);
        panelAddBahan.setLayout(panelAddBahanLayout);
        panelAddBahanLayout.setHorizontalGroup(
            panelAddBahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddBahanLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelAddBahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddBahanLayout.createSequentialGroup()
                        .addGroup(panelAddBahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaKategoriField, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaBahan)
                            .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(namaBahan2)
                        .addGap(328, 328, 328))
                    .addGroup(panelAddBahanLayout.createSequentialGroup()
                        .addGroup(panelAddBahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tambahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taggableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelAddBahanLayout.setVerticalGroup(
            panelAddBahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddBahanLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelAddBahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAddBahanLayout.createSequentialGroup()
                        .addComponent(namaBahan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaKategoriField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(ket)
                        .addGap(18, 18, 18)
                        .addComponent(taggableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(panelAddBahanLayout.createSequentialGroup()
                        .addComponent(namaBahan2)
                        .addGap(275, 275, 275)))
                .addComponent(tambahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        jLabel2.setText("Kategori");

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel4.setText("Tambah");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAddBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(panelAddBahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        // TODO add your handling code here:
        kategori = getAllDataKategoriField();
//        taggables = getAllDataTaggableField();
//        taggableRepo.addTaggable(taggables);
        kategoriRepo.addKategori(kategori);
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void taggableComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taggableComboFocusGained
        // TODO add your handling code here:
        
          DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        List<Taggable> taggableList = taggableRepo.getAllTaggable();
        
        for (int i = 0; i < taggableList.size(); i++) {
            Taggable taggableValue = taggableList.get(i);
            comboBoxModel.addElement(taggableValue.getTipe_taggable());
        }
        
        taggableCombo.setModel( comboBoxModel);
    }//GEN-LAST:event_taggableComboFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahKategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ket;
    private javax.swing.JLabel namaBahan;
    private javax.swing.JLabel namaBahan2;
    private javax.swing.JTextField namaKategoriField;
    private javax.swing.JPanel panelAddBahan;
    private javax.swing.JComboBox<String> taggableCombo;
    private javax.swing.JButton tambahBtn;
    // End of variables declaration//GEN-END:variables
}
